### ISSUE TITLE
DBML interactive doesn't show indexes

### ISSUE THREAD

**Issue by SpeedyGonzaless** [ggrossetie/asciidoctor-kroki#408]
When I am using dbml I would like to see indexes as for dbml
![image](https://user-images.githubusercontent.com/40829475/228195394-d930af52-39a3-441f-a5c1-c3055384c286.png)
but instead I cannot see pop-up with indexes
![image](https://user-images.githubusercontent.com/40829475/228195790-d890bb9f-f972-4d94-b422-08f489944f45.png)
Or maybe I am doing something wrong?
I used the same code for adoc and for this website https://dbdiagram.io/d

```
[dbml,database,svg,options="interactive"]
Table tag {
    id uuid [not null]
    name text [not null]

    indexes {
        (id) [pk]
        (name) [unique]
    }
}

Table tag2 {
    id uuid [not null]
    tag_id uuid [ref: > tag.id]
}
----
```

**Comment by ggrossetie** [comment]
Kroki is using https://github.com/softwaretechnik-berlin/dbml-renderer to render DBML.
I don't think the rendering engine used at https://dbdiagram.io/d is open source.

In the future please join https://kroki.zulipchat.com/ to ask questions.
