### ISSUE TITLE
Mermaird failed

### ISSUE THREAD

**Issue by cfdomingues** [ggrossetie/asciidoctor-kroki#425]
I always have this error when try to render a mermaid flow

Skipping mermaid block. GET https://kroki.io/mermaid/svg/eNpdzDEOgzAMBdCdU3iJKGqj7qiKhJqBiYGIA6SVVWUgUe1QBsTdazLi8f_3rdQGIYbcwgY143fB-EYb_If8XMMOu1LVKa5AbkgZIf2Q4Nm7W-9cC1LPmCVxyBxSLE5abcy1gMmOjxfdzWViJG199no8XnNuihUkVsvksN3ZdpFXpOYPkbw2zg==?id=rar_and_raa_flow - server returns an empty response or a 404 status code

**Comment by ggrossetie** [comment]
If you are using the public instance https://kroki.io the mermaid service is currently unavailable.

As a workaround, you can use your own instance.

**Comment by cfdomingues** [comment]
@ggrossetie  You are right I'm using https://kroki.io/.
I installed my own instance and don't have any issues.
Thanks
