### ISSUE TITLE
Help narrow down the causes when server responds with error

### ISSUE THREAD

**Issue by sransara** [ggrossetie/asciidoctor-kroki#430]
I was getting errors like:

```
Skipping mermaid block. GET https://... - server returns an empty response or a 404 status code
```

Digging in, I found out that the server was responding with `500` error code.

It would be helpful if we could see what is the error code from the server to narrow down the root of the issue.

Environment: Node.js

**Comment by ggrossetie** [comment]
I would like to reproduce this issue to make sure that we are covering every cases. Do you have a reproduction case or was it a temporary failure on your infrastructure or on kroki.io?

**Comment by sransara** [comment]
> Do you have a reproduction case or was it a temporary failure on your infrastructure or on kroki.io?

I'm sorry, I don't have small reproducible example. I was using krok.io. I believe it was a temporary failure over there.

**Comment by ggrossetie** [comment]
I can reproduce this issue using http://httpstat.us/500
