### ISSUE TITLE
Formulas using PlantUML cannot display correctly

### ISSUE THREAD

**Issue by Pigmented** [ggrossetie/asciidoctor-kroki#433]
- Can Asciidoctor-Kroki support formulas using PlantUML now?

- Previously, with the asciidoctor-diagram plugin, the following formulas could be displayed:

![image](https://github.com/ggrossetie/asciidoctor-kroki/assets/129073565/13557195-6a41-4245-b853-071b7ad00cad)
![image](https://github.com/ggrossetie/asciidoctor-kroki/assets/129073565/c75d10d8-8961-4aee-9299-4c926796b1d5)

- After switching to Kroki, the formulas cannot be displayed correctly in both HTML and PDF.

![image](https://github.com/ggrossetie/asciidoctor-kroki/assets/129073565/736a7955-60ac-49a8-9fc9-52e9eb905a7d)

-  I copyied the formulas from the PlantUML site (https://plantuml.com/ascii-math) to Kroki's test page (https://kroki.io/#try) ; it didn't display correctly."

![image](https://github.com/ggrossetie/asciidoctor-kroki/assets/129073565/41060c05-09df-49bc-aac9-401ee28ab32c)
![image](https://github.com/ggrossetie/asciidoctor-kroki/assets/129073565/ba3ff86d-5004-44be-a3be-20a15997c13b)

- But other PlantUML diagrams without formulas all display correctly.

**Comment by ggrossetie** [comment]
This is actually a duplicate.
See: https://github.com/yuzutech/kroki/issues/442

**Comment by Pigmented** [comment]
I've read [https://github.com/yuzutech/kroki/issues/442], formulas still cannot be properly displayed, and no warnings or information was given.
